### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alekzvik** [laz-rs/laz-rs-wasm#2]
Hi @tmontaigu,

It's a great project and I'd love to use the WASM bindings in a library. Unfortunately, the license is missing. I expect that since all the other `laz-rs` projects are distributed under Apache 2.0, this one is too, but it is not explicit.

Could you add an explicit license file?

**Comment by alekzvik** [comment]
Correction: python bindings use MIT license

**Comment by tmontaigu** [comment]
I'll add one

**Comment by alekzvik** [comment]
@tmontaigu, thank you! I can make a PR if you tell me which license you want, as I do not want to assume.

**Comment by tmontaigu** [comment]
I just added the MIT License

On another note, this project is pretty bare bones compared to what laz-rs, for example parallel decompression seems missing, which is something important to get good perfomance so I guess that could be added

**Comment by alekzvik** [comment]
I might look at exposing it later, I've looked into it and it seems wasm bindings play well with rayon (I am new to rust, so do not trust me on this)
In the meantime, thanks for adding a license!
